import { Test, TestingModule } from '@nestjs/testing';
import { NotFoundException } from '@nestjs/common';
import { TeacherInsightsService } from '../teacher-insights.service';
import { TeacherInsightsRepository } from '../teacher-insights.repository';
import { AiProvider } from '../../providers/ai.provider';
import { AiPromptService } from '../../services/ai-prompt.service';
import { TeacherMetricsSummaryDto } from '../dto/teacher-metrics-summary.dto';

describe('TeacherInsightsService', () => {
  let service: TeacherInsightsService;
  let repository: jest.Mocked<TeacherInsightsRepository>;
  let aiProvider: jest.Mocked<AiProvider>;
  let aiPromptService: jest.Mocked<AiPromptService>;

  const mockTeacherId = '11111111-1111-1111-1111-111111111111';
  const mockStudentIds = ['22222222-2222-2222-2222-222222222222'];
  const mockPeriodStart = new Date('2026-08-01T00:00:00Z');
  const mockPeriodEnd = new Date('2026-08-08T00:00:00Z');

  const mockMetricsSummary: TeacherMetricsSummaryDto = {
    teacherId: mockTeacherId,
    periodStart: mockPeriodStart.toISOString(),
    periodEnd: mockPeriodEnd.toISOString(),
    studentCount: 1,
    activeStudents: 1,
    cognitive: {
      accuracy: 0.85,
      reactionTime: 1200,
      cognitiveLoad: 0.4,
      memoryRetention: 0.9,
      attentionSpan: 0.8,
    },
    gameAttempts: {
      totalAttempts: 10,
      successRate: 0.8,
      averageScore: 85,
      quickCompletionRate: 0.3,
      byGameType: [],
    },
    contentProgress: {
      averageProgress: 0.75,
      completedCount: 5,
      strugglingContent: [],
    },
  };

  const mockReport = {
    report_id: 'report-uuid',
    teacher_id: mockTeacherId,
    period_start: mockPeriodStart,
    period_end: mockPeriodEnd,
    student_count: 1,
    active_students: 1,
    metrics_summary: mockMetricsSummary as any,
    report_text: 'Report text generated by AI',
    status: 'GENERATED',
    created_at: new Date(),
  };

  beforeEach(async () => {
    const mockRepo = {
      findTeacherIdsWithStudents: jest.fn().mockResolvedValue([mockTeacherId]),
      findStudentIdsForTeacher: jest.fn().mockResolvedValue(mockStudentIds),
      buildWeeklyMetricsSummary: jest.fn().mockResolvedValue(mockMetricsSummary),
      saveReport: jest.fn().mockResolvedValue(mockReport),
      findReportsByTeacher: jest.fn().mockResolvedValue([mockReport]),
    };

    const mockAi = {
      analyzeTeacherWeeklyMetrics: jest.fn().mockResolvedValue('Report text generated by AI'),
    };

    const mockPrompt = {
      getPrompt: jest.fn().mockResolvedValue('System prompt instruction'),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        TeacherInsightsService,
        { provide: TeacherInsightsRepository, useValue: mockRepo },
        { provide: AiProvider, useValue: mockAi },
        { provide: AiPromptService, useValue: mockPrompt },
      ],
    }).compile();

    service = module.get<TeacherInsightsService>(TeacherInsightsService);
    repository = module.get(TeacherInsightsRepository);
    aiProvider = module.get(AiProvider);
    aiPromptService = module.get(AiPromptService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('generateWeeklyReportsForAllTeachers', () => {
    it('should generate reports for all returned teachers', async () => {
      const result = await service.generateWeeklyReportsForAllTeachers(
        mockPeriodStart,
        mockPeriodEnd,
      );

      expect(repository.findTeacherIdsWithStudents).toHaveBeenCalledTimes(1);
      expect(result).toEqual({ processed: 1, failed: 0 });
    });

    it('should track failures per teacher without aborting the batch', async () => {
      repository.findTeacherIdsWithStudents.mockResolvedValue(['t1', 't2']);
      repository.findStudentIdsForTeacher
        .mockResolvedValueOnce(mockStudentIds)
        .mockRejectedValueOnce(new Error('DB error for t2'));

      const result = await service.generateWeeklyReportsForAllTeachers(
        mockPeriodStart,
        mockPeriodEnd,
      );

      expect(result).toEqual({ processed: 1, failed: 1 });
    });
  });

  describe('generateWeeklyReportForTeacher', () => {
    it('should build metrics, pass to AiProvider, and save report', async () => {
      const report = await service.generateWeeklyReportForTeacher(
        mockTeacherId,
        mockPeriodStart,
        mockPeriodEnd,
      );

      expect(repository.findStudentIdsForTeacher).toHaveBeenCalledWith(mockTeacherId);
      expect(repository.buildWeeklyMetricsSummary).toHaveBeenCalledWith(
        mockTeacherId,
        mockStudentIds,
        mockPeriodStart,
        mockPeriodEnd,
      );
      expect(aiPromptService.getPrompt).toHaveBeenCalledWith(
        'teacher-insights',
        'WEEKLY_REPORT',
        expect.any(String),
      );
      expect(aiProvider.analyzeTeacherWeeklyMetrics).toHaveBeenCalledWith(
        'System prompt instruction',
        mockMetricsSummary,
      );
      expect(repository.saveReport).toHaveBeenCalledWith({
        teacherId: mockTeacherId,
        periodStart: mockPeriodStart,
        periodEnd: mockPeriodEnd,
        studentCount: 1,
        activeStudents: 1,
        metricsSummary: mockMetricsSummary,
        reportText: 'Report text generated by AI',
      });
      expect(report).toEqual(mockReport);
    });

    it('should throw NotFoundException if teacher has no linked students', async () => {
      repository.findStudentIdsForTeacher.mockResolvedValueOnce([]);

      await expect(
        service.generateWeeklyReportForTeacher(mockTeacherId, mockPeriodStart, mockPeriodEnd),
      ).rejects.toThrow(NotFoundException);
    });
  });

  describe('getReportsForTeacher', () => {
    it('should call repository.findReportsByTeacher', async () => {
      const reports = await service.getReportsForTeacher(mockTeacherId, 5);

      expect(repository.findReportsByTeacher).toHaveBeenCalledWith(mockTeacherId, 5);
      expect(reports).toEqual([mockReport]);
    });
  });
});
